---
- name: Manage Virtual Machine Extension
  hosts:
    - jumpboxes
  tags:
    - "azure"
    - "vmext"
  gather_facts: no
  pre_tasks:
    - name: search log analytics workspace
      azure_rm_loganalyticsworkspace_facts:
        ad_user: "{{ azure_ad_user | default(omit) }}"
        password: "{{ azure_password | default(omit) }}"
        subscription_id: "{{ azure_subscription_id | default(omit) }}"
        client_id: "{{ azure_client_id | default(omit) }}"
        secret: "{{ azure_secret | default(omit) }}"
        tenant: "{{ azure_tenant | default(omit) }}"
        resource_group: "{{ law_resource_group | default(omit, true) }}"
        name: "{{ law_name }}"
        show_intelligence_packs: true
        show_management_groups: true
        show_usages: true
        show_shared_keys: true
      delegate_to: localhost
      register: azure_law_facts

    - set_fact:
        Azure_workspace_id: "{{ azure_law_facts.workspaces[0].customer_id }}"
        Azure_workspace_sharedkey: "{{ azure_law_facts.workspaces[0].shared_keys.primary_shared_key }}"
  roles:
    - {role: azure_vmext, delegate_to: localhost, tags: ["azure", "vmext"]}
...
