---
# tasks file for ansible-pan-galaxy/

# install required libraries
- name: Install pan-python required library
  pip:
    name: pan-python
  become: yes
- name: Install pandevice required library
  pip:
    name: pandevice
  become: yes
- name: Install xmltodict required library
  pip:
    name: xmltodict
  become: yes
