---
- name: Delete virtual network gateway
  azure_rm_virtualnetworkgateway:
    ad_user: "{{ azure_ad_user | default(omit) }}"
    password: "{{ azure_password | default(omit) }}"
    subscription_id: "{{ azure_subscription_id | default(omit) }}"
    client_id: "{{ azure_client_id | default(omit) }}"
    secret: "{{ azure_secret | default(omit) }}"
    tenant: "{{ azure_tenant | default(omit) }}"
    name: "{{ vgw.name }}"
    resource_group: "{{ vgw.resource_group }}"
    virtual_network: "{{ vgw.virtual_network }}"
    state: "absent"
  register: deletedvgw
...
