---
- name: Ensure ssh dir exist
  file:
    path: "~/.ssh"
    state: directory
    mode: 0750
  delegate_to: localhost

- name: Ensure known_hosts file exist
  copy:
    content: ""
    dest: "~/.ssh/known_hosts"
    force: no
    mode: 0640
  delegate_to: localhost

- name: Remove ip
  shell: "ssh-keygen -R {{ public_ipv4_address }}"
  failed_when: false
  when:
    - force == True
  delegate_to: localhost

- name: Search ip
  shell: "ssh-keygen -F {{ public_ipv4_address }}"
  failed_when: false
  changed_when: false
  register: searchip
  delegate_to: localhost

- name: Insert
  shell: "ssh-keyscan {{ public_ipv4_address }} >> ~/.ssh/known_hosts"
  when:
    - searchip.rc != 0
  delegate_to: localhost
...
