---
- name: Login to azure
  command:
    argv:
      - "az"
      - "login"
      - "--service-principal"
      - "-u"
      - "{{ azure_client_id }}"
      - "-p"
      - "{{ azure_secret }}"
      - "-t"
      - "{{ azure_tenant }}"
  delegate_to: localhost

- name: Select subscription
  command:
    argv:
      - "az"
      - "account"
      - "set"
      - "-s"
      - "{{ sentinel.law.subscriptionid }}"
  delegate_to: localhost

- name: List solution
  command:
    argv:
      - "az"
      - "resource"
      - "list"
      - "--resource-type"
      - "Microsoft.OperationsManagement/solutions"
      - "--name"
      - "{{ sentinel.law.name | default('', true) }}"
  register: azure_sentinel_facts
  delegate_to: localhost

- name: Push arm template
  template:
    src: "sentinel.json.j2"
    dest: "/tmp/sentinel.json"
  delegate_to: localhost

- name: Validate template
  command:
    argv:
      - "az"
      - "group"
      - "deployment"
      - "validate"
      - "-g"
      - "{{ sentinel.resource_group }}"
      - "--template-file"
      - "/tmp/sentinel.json"
  delegate_to: localhost

- name: Create sentinel solution 
  command:
    argv:
      - "az"
      - "group"
      - "deployment"
      - "create"
      - "-g"
      - "{{ sentinel.resource_group }}"
      - "--template-file"
      - "/tmp/sentinel.json"
  register: createsentinel
  delegate_to: localhost
...
