---
- set_fact:
    tags_list: "{{ tags_list | default([]) |
    union([[tag.key,tag.value]|join(':')]) }}"
  loop: "{{ lookup('dict', law.tags | default({})) }}"
  loop_control:
    loop_var: "tag"

- name: Get log analytics workspace
  azure_rm_loganalyticsworkspace_facts:
    ad_user: "{{ azure_ad_user | default(omit) }}"
    password: "{{ azure_password | default(omit) }}"
    subscription_id: "{{ azure_subscription_id | default(omit) }}"
    client_id: "{{ azure_client_id | default(omit) }}"
    secret: "{{ azure_secret | default(omit) }}"
    tenant: "{{ azure_tenant | default(omit) }}"
    resource_group: "{{ law.resource_group }}"
    tags: "{{ tags_list | default(omit) }}"
    name: "{{ law.name | default(omit) }}"
    show_intelligence_packs: "{{ law.show_intelligence_packs |
    default(true, true) }}"
    show_usages: "{{ law.show_usages | default(true, true) }}"
  register: azure_law_facts

- name: Delete log analytics workspace
  azure_rm_loganalyticsworkspace:
    ad_user: "{{ azure_ad_user | default(omit) }}"
    password: "{{ azure_password | default(omit) }}"
    subscription_id: "{{ azure_subscription_id | default(omit) }}"
    client_id: "{{ azure_client_id | default(omit) }}"
    secret: "{{ azure_secret | default(omit) }}"
    tenant: "{{ azure_tenant | default(omit) }}"
    name: "{{ law.name }}"
    resource_group: "{{ law.resource_group }}"
    state: "absent"
  register: deletedlaw
...
