---
- set_fact:
    tags_list: "{{ tags_list | default([]) |
    union([[tag.key,tag.value]|join(':')]) }}"
  loop: "{{ lookup('dict', avs.tags | default({})) }}"
  loop_control:
    loop_var: "tag"

- name: Get availability set
  azure_rm_availabilityset_facts:
    ad_user: "{{ azure_ad_user | default(omit) }}"
    password: "{{ azure_password | default(omit) }}"
    subscription_id: "{{ azure_subscription_id | default(omit) }}"
    client_id: "{{ azure_client_id | default(omit) }}"
    secret: "{{ azure_secret | default(omit) }}"
    tenant: "{{ azure_tenant | default(omit) }}"
    resource_group: "{{ avs.resource_group }}"
    tags: "{{ tags_list | default(omit, true) }}"
    name: "{{ avs.name | default(omit) }}"
  register: azure_avs_facts

- name: Delete availability set
  azure_rm_availabilityset:
    ad_user: "{{ azure_ad_user | default(omit) }}"
    password: "{{ azure_password | default(omit) }}"
    subscription_id: "{{ azure_subscription_id | default(omit) }}"
    client_id: "{{ azure_client_id | default(omit) }}"
    secret: "{{ azure_secret | default(omit) }}"
    tenant: "{{ azure_tenant | default(omit) }}"
    name: "{{ avs.name }}"
    resource_group: "{{ avs.resource_group }}"
    state: "absent"
  register: deletedavs
...
