---
- name: Get log analytics workspace
  azure_rm_resource_facts:
    ad_user: "{{ azure_ad_user | default(omit) }}"
    password: "{{ azure_password | default(omit) }}"
    subscription_id: "{{ azure_subscription_id | default(omit) }}"
    client_id: "{{ azure_client_id | default(omit) }}"
    secret: "{{ azure_secret | default(omit) }}"
    tenant: "{{ azure_tenant | default(omit) }}"
    resource_group: "{{ res.resource_group }}"
    resource_name: "{{ res.name | default(omit) }}"
  register: azure_res_facts

- name: Delete log analytics workspace
  azure_rm_resource:
    ad_user: "{{ azure_ad_user | default(omit) }}"
    password: "{{ azure_password | default(omit) }}"
    subscription_id: "{{ azure_subscription_id | default(omit) }}"
    client_id: "{{ azure_client_id | default(omit) }}"
    secret: "{{ azure_secret | default(omit) }}"
    tenant: "{{ azure_tenant | default(omit) }}"
    provider: "{{ res.provider }}"
    resource_name: "{{ res.name }}"
    resource_group: "{{ res.resource_group }}"
    resource_type: "{{ res.resource_type }}"
    state: "absent"
  register: deletedres
...
