---
- set_fact:
    tags_list: "{{ tags_list | default([]) |
    union([[tag.key,tag.value]|join(':')]) }}"
  loop: "{{ lookup('dict', sa.tags) }}"
  loop_control:
    loop_var: "tag"

- name: Get storage account
  azure_rm_storageaccount_facts:
    client_id: "{{ azure_client_id | default(omit) }}"
    subscription_id: "{{ azure_subscription_id | default(omit) }}"
    secret: "{{ azure_secret | default(omit) }}"
    tenant: "{{ azure_tenant | default(omit) }}"
    resource_group: "{{ sa.resource_group | default(omit) }}"
    show_connection_string: "{{ sa.show_connection_string |
    default(true, true) }}"
    tags: "{{ tags_list | default(omit) }}"
    name: "{{ sa.name | default(omit) }}"
  register: azure_sa_facts

- name: Create storage account
  azure_rm_storageaccount:
    client_id: "{{ azure_client_id | default(omit) }}"
    subscription_id: "{{ azure_subscription_id | default(omit) }}"
    secret: "{{ azure_secret | default(omit) }}"
    tenant: "{{ azure_tenant | default(omit) }}"
    name: "{{ sa.name }}"
    access_tier: "{{ sa.access_tier | default('Hot', true) }}"
    account_type: "{{ sa.account_type | default('StandardSSD_LRS', true) }}"
    blob_cors: "{{ sa.blob_cors | default([], true) }}"
    force_delete_nonempty: "{{ sa.force_delete_nonempty | default(false, true) }}"
    https_only: "{{ sa.https_only | default(true, true) }}"
    kind: "{{ sa.kind | default(omit, true) }}"
    resource_group: "{{ sa.resource_group }}"
    state: "present"
    tags: "{{ sa.tags | default(omit, true) }}"
    append_tags: false
  register: createsa
...
