---
- name: Get subnet
  azure_rm_subnet_facts:
    ad_user: "{{ azure_ad_user | default(omit) }}"
    password: "{{ azure_password | default(omit) }}"
    subscription_id: "{{ azure_subscription_id | default(omit) }}"
    client_id: "{{ azure_client_id | default(omit) }}"
    secret: "{{ azure_secret | default(omit) }}"
    tenant: "{{ azure_tenant | default(omit) }}"
    resource_group: "{{ subnet.resource_group }}"
    virtual_network_name: "{{ subnet.virtual_network_name }}"
    name: "{{ subnet.name | default(omit, true) }}"
  register: azure_subnet_facts
  failed_when: false

- name: Create subnet
  azure_rm_subnet:
    ad_user: "{{ azure_ad_user | default(omit) }}"
    password: "{{ azure_password | default(omit) }}"
    subscription_id: "{{ azure_subscription_id | default(omit) }}"
    client_id: "{{ azure_client_id | default(omit) }}"
    secret: "{{ azure_secret | default(omit) }}"
    tenant: "{{ azure_tenant | default(omit) }}"
    name: "{{ subnet.name }}"
    address_prefix_cidr: "{{ subnet.address_prefix_cidr }}"
    virtual_network_name: "{{ subnet.virtual_network_name }}"
    resource_group: "{{ subnet.resource_group }}"
    security_group: "{{ subnet.security_group | default(omit, true) }}"
    route_table: "{{ subnet.route_table | default(omit, true) }}"
    state: "present"
  register: createsubnet
...
