---
- set_fact:
    tags_list: "{{ tags_list | default([]) |
    union([[tag.key,tag.value]|join(':')]) }}"
  loop: "{{ lookup('dict', lb.tags | default({})) }}"
  loop_control:
    loop_var: "tag"

- name: Get load balancer
  azure_rm_loadbalancer_facts:
    ad_user: "{{ azure_ad_user | default(omit) }}"
    password: "{{ azure_password | default(omit) }}"
    subscription_id: "{{ azure_subscription_id | default(omit) }}"
    client_id: "{{ azure_client_id | default(omit) }}"
    secret: "{{ azure_secret | default(omit) }}"
    tenant: "{{ azure_tenant | default(omit) }}"
    resource_group: "{{ lb.resource_group }}"
    tags: "{{ tags_list | default(omit) }}"
    name: "{{ lb.name | default(omit) }}"
  register: azure_lb_facts

- name: Print load balancer
  debug:
    var: azure_lb_facts.azure_loadbalancers
...
