---
- set_fact:
    tags_list: "{{ tags_list | default([]) |
    union([[tag.key,tag.value]|join(':')]) }}"
  loop: "{{ lookup('dict', vmext.tags | default({}, true)) }}"
  loop_control:
    loop_var: "tag"

- name: Get virtual machine extension
  azure_rm_virtualmachineextension_info:
    ad_user: "{{ azure_ad_user | default(omit) }}"
    password: "{{ azure_password | default(omit) }}"
    subscription_id: "{{ azure_subscription_id | default(omit) }}"
    client_id: "{{ azure_client_id | default(omit) }}"
    secret: "{{ azure_secret | default(omit) }}"
    tenant: "{{ azure_tenant | default(omit) }}"
    resource_group: "{{ vmext.resource_group }}"
    tags: "{{ tags_list | default(omit) }}"
    name: "{{ vmext.name | default(omit) }}"
    virtual_machine_name: "{{ vmext.vm_name }}"
  register: azure_vmext_facts
  failed_when: false

- name: Create virtual machine extension
  azure_rm_virtualmachineextension:
    ad_user: "{{ azure_ad_user | default(omit) }}"
    password: "{{ azure_password | default(omit) }}"
    subscription_id: "{{ azure_subscription_id | default(omit) }}"
    client_id: "{{ azure_client_id | default(omit) }}"
    secret: "{{ azure_secret | default(omit) }}"
    tenant: "{{ azure_tenant | default(omit) }}"
    name: "{{ vmext.name }}"
    resource_group: "{{ vmext.resource_group }}"
    protected_settings: "{{ vmext.protected_settings | default(omit, true) }}"
    settings: "{{ vmext.settings | default(omit, true) }}"
    publisher: "{{ vmext.publisher }}"
    virtual_machine_name: "{{ vmext.vm_name }}"
    virtual_machine_extension_type: "{{ vmext.virtual_machine_extension_type }}"
    type_handler_version: "{{ vmext.type_handler_version }}"
    state: "present"
  register: createvmext
...
