---
- set_fact:
    tags_list: "{{ tags_list | default([]) |
    union([[tag.key,tag.value]|join(':')]) }}"
  loop: "{{ lookup('dict', rg.tags | default({}, true)) }}"
  loop_control:
    loop_var: "tag"

- name: Get resource group
  azure_rm_resourcegroup_facts:
    ad_user: "{{ azure_ad_user | default(omit) }}"
    password: "{{ azure_password | default(omit) }}"
    subscription_id: "{{ azure_subscription_id | default(omit) }}"
    client_id: "{{ azure_client_id | default(omit) }}"
    secret: "{{ azure_secret | default(omit) }}"
    tenant: "{{ azure_tenant | default(omit) }}"
    list_resources: false
    tags: "{{ tags_list | default(omit) }}"
    name: "{{ rg.name | default(omit) }}"
  register: azure_rg_facts

- name: Create resource group
  azure_rm_resourcegroup:
    ad_user: "{{ azure_ad_user | default(omit) }}"
    password: "{{ azure_password | default(omit) }}"
    subscription_id: "{{ azure_subscription_id | default(omit) }}"
    client_id: "{{ azure_client_id | default(omit) }}"
    secret: "{{ azure_secret | default(omit) }}"
    tenant: "{{ azure_tenant | default(omit) }}"
    name: "{{ rg.name }}"
    append_tags: false
    location: "{{ rg.location }}"
    state: "present"
    tags: "{{ rg.tags | default(omit) }}"
  register: createrg
...
