---
- set_fact:
    tags_list: "{{ tags_list | default([]) |
    union([[tag.key,tag.value]|join(':')]) }}"
  loop: "{{ lookup('dict', nic.tags | default({})) }}"
  loop_control:
    loop_var: "tag"

- name: Get network interface
  azure_rm_networkinterface_facts:
    client_id: "{{ azure_client_id | default(omit) }}"
    subscription_id: "{{ azure_subscription_id | default(omit) }}"
    secret: "{{ azure_secret | default(omit) }}"
    tenant: "{{ azure_tenant | default(omit) }}"
    resource_group: "{{ nic.resource_group }}"
    tags: "{{ tags_list | default(omit) }}"
    name: "{{ nic.name | default(omit) }}"
  register: azure_nic_facts

- name: Print network interface
  debug:
    var: azure_nic_facts.networkinterfaces
...
